language: ruby
rvm:
- '2.3.1'
- '2.4.2'
sudo: false
cache:
  bundler: true
  yarn: true
  directories:
  - vendor/assets/bower_components
addons:
  postgresql: '9.4'
env:
  matrix:
  - TEST_SUITE=spec
  - TEST_SUITE=spec:javascript
  - TEST_SUITE=spec:compile
bundler_args: --no-deployment
before_install: source tools/ci/before_install.sh
before_script: bundle exec rake $TEST_SUITE:setup
script: bundle exec rake $TEST_SUITE
before_cache:
- cp bower.json vendor/assets/bower_components
after_script: source tools/ci/after_install.sh
